[2025-04-04T14:36:03.482+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509
[2025-04-04T14:36:03.483+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job'
[2025-04-04T14:36:03.561+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509
[2025-04-04T14:36:03.562+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job'
[2025-04-04T14:36:03.611+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_distributed_spark_etl.run_spark_distributed_job scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T14:36:03.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_distributed_spark_etl.run_spark_distributed_job scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T14:36:03.626+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2025-04-04T14:36:03.668+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_spark_distributed_job> on 2025-04-03 00:00:00+00:00
[2025-04-04T14:36:03.674+0000] {standard_task_runner.py:57} INFO - Started process 31 to run task
[2025-04-04T14:36:03.697+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'daily_distributed_spark_etl', 'run_spark_distributed_job', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_distributed_etl.py', '--cfg-path', '/tmp/tmp4awj3lpk']
[2025-04-04T14:36:03.702+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask run_spark_distributed_job
[2025-04-04T14:36:03.817+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509
[2025-04-04T14:36:03.818+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=daily_distributed_spark_etl/run_id=scheduled__2025-04-03T00:00:00+00:00/task_id=run_spark_distributed_job'
[2025-04-04T14:36:03.820+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_distributed_spark_etl.run_spark_distributed_job scheduled__2025-04-03T00:00:00+00:00 [running]> on host b3e955a18a01
[2025-04-04T14:36:03.965+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='data.team@example.com' AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='daily_distributed_spark_etl' AIRFLOW_CTX_TASK_ID='run_spark_distributed_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T14:36:03.966+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-04T14:36:03.967+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "ðŸ”¥ Lancement du job Spark..." && docker exec spark-app spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/spark_jobs/process_users.py']
[2025-04-04T14:36:03.980+0000] {subprocess.py:86} INFO - Output:
[2025-04-04T14:36:03.986+0000] {subprocess.py:93} INFO - ðŸ”¥ Lancement du job Spark...
[2025-04-04T14:36:04.274+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-04-04T14:36:04.276+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-04T14:36:04.293+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-04T14:36:04.303+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_distributed_spark_etl, task_id=run_spark_distributed_job, execution_date=20250403T000000, start_date=20250404T143603, end_date=20250404T143604
[2025-04-04T14:36:04.346+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task run_spark_distributed_job (Bash command failed. The command returned a non-zero exit code 1.; 31)
[2025-04-04T14:36:04.386+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-04T14:36:04.437+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
